name: Build Kivy Android App
on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında çalışmasını sağlar
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 8 
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Download Database from Releases
        run: |
          curl -sL -o kuran_uyg_genel_data.db "https://github.com/mes41c/kuranuygulamasi/releases/download/v1.0-db/kuran_uyg_genel_data.db"
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer -v android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
